#:kivy 1.0
<MyBoxLayout>
    do_default_tab: False
    #tab_pos: 'bottom_mid'

    TabbedPanelItem: 
        text: "TAB-1"
        Label:
            text: "Hello"
    
    TabbedPanelItem: 
        text: "TAB-2"
        BoxLayout:
            Label:
                text: "Press the button =>"
            Button:
                text: "Click me"
    
    TabbedPanelItem: 
        text: "TAB-3"
        Image:
            source: 'Image/photo.jpg'   
    